### ISSUE TITLE
ports in docker-compose.yml seem to be inconsistent

### ISSUE THREAD

**Issue by philipphutterer** [dbpedia/databus#10]
it seems that the main gstore container port changed from 80 to 8080 with commit e8c89c0df69cb36ec876dc6610d53730f62d6acc but the `DATABUS_DATABASE_URL` environment variable for the databus container is missing this change (it still points to 80).

this results in a databus container waiting endlessly for gstore on the wrong port.

**Comment by holycrab13** [comment]
Thanks, fixed it!
