### ISSUE TITLE
files certificates expired

### ISSUE THREAD

**Issue by giacbrd** [dbpedia/databus#114]
The security certificates of files downloadable through https, from databus, expired on the 17th.
E.g. https://databus.dbpedia.org/dbpedia/mappings/instance-types/2022.12.01/instance-types_inference=transitive_lang=it.ttl.bzip2 would return security warnings from any browser.
The expired certificate is for https://archivo.dbpedia.org/

**Comment by JJ-Author** [comment]
thank you for the reporting. I fixed it and it should be working.
