### ISSUE TITLE
API not working any more?

### ISSUE THREAD

**Issue by giannou** [dbpedia/databus#12]
Up until a couple days ago the API for uploading data to the databus was working fine. But now all data from the databus are gone and the API stopped working. Is there something that can be done from the user's side to fix this?

**Comment by holycrab13** [comment]
Hi, are you using the dev databus at https://dev.databus.dbpedia.org or the DBpedia Databus at https://databus.dbpedia.org?

The dev databus is for development and will be wiped quite frequently. Also the API syntax might still change. Until further notice I would not recommend to use this instance for anything more than testing and exploring features.

Afaik, the DBpedia Databus (https://databus.dbpedia.org) will be mainly used for DBpedia releases and official mods and extensions. 

The recommended course of action is to deploy a Databus instance specifically for your project using docker (I could help with that).

**Comment by holycrab13** [comment]
Sorry about the confusion, @JJ-Author and I should have communicated better!

The dev databus should not be the place to host any official data. Some details are still subject to change and there might still be bugs hidden that can potentially break things internally. I would like to reserve the right to restart that whole system with a clean database for development purposes.

 @JJ-Author can we maybe set up another instance for LOD-GEOSS? Could be done on the same server with a different DNS like https://lodgeoss.databus.dbpedia.org. I can set up the instance and leave it untouched!

**Comment by giannou** [comment]
We are not uploading any official data yet, so emptying the dev databus every now and then is not a problem for me. But the changes in the API are a problem because I am basically writing a suite in R that will be an interface for models uploading and downloading data automatically (without user intervention). My code uses the API so any upstream changes will be constantly breaking it. Anyhow, let's see what @JJ-Author's thought are, thanks for your help!
