### ISSUE TITLE
shacl from databus ontology does not resolve

### ISSUE THREAD

**Issue by JJ-Author** [dbpedia/databus#127]
the following shacl is missing. dont know whether its missing or just an unjustified link in the ontology https://raw.githubusercontent.com/dbpedia/databus/master/model/generated/shacl/version.shacl

**Comment by holycrab13** [comment]
The current correct link is ```.../shacl/dataid.ttl```
However, I would rather refactor the generator scripts to align it with the naming of the rest of the databus
