### ISSUE TITLE
can not unset "create group" checkmark once set in publish wizard

### ISSUE THREAD

**Issue by JJ-Author** [dbpedia/databus#13]

**Comment by holycrab13** [comment]
Are you sure that you already had a group on that account?
Unset is disabled if there are no existing group so far. 

Bugs are:
* Groups of the publishing user were not fetched correctly
* Checkmark did not toggle to "true" automatically

**Comment by JJ-Author** [comment]
true I had no group yet. 

so it is the latter:

**Comment by holycrab13** [comment]
known publishing page bug, will be resolved in 2.1.0
