### ISSUE TITLE
https://databus.dbpedia.org/ currently down

### ISSUE THREAD

**Issue by cem-okulmus** [dbpedia/databus#137]
I wanted to download the latest core of DBPedia, and all existing scripts that I can find point to the databus site, which however seems to be down? For instance, this URL is stated to link to the relevant datasets: 
https://databus.dbpedia.org/dbpedia/collections/latest-core
This returns a 404: Not Found Error, though. 

![image](https://github.com/dbpedia/databus/assets/36513234/838f7f05-0e0e-4bf5-a73a-35130b49c4ed)

It seems to affect pretty much all aspects of the site, so I am wondering if this just regular maintenance? If so, then this is a non-issue. Perhaps making such maintenance action clear to visitors would be helpful, though.

**Comment by manonthegithub** [comment]
Hi @cem-okulmus please try again, should be working now
