### ISSUE TITLE
documentation update: needs fix at setting up local environment

### ISSUE THREAD

**Issue by Tethet-18** [dbpedia/databus#146]
The documentation says to be in root folder to setup the local environment but we need to be in the devenv folder. Also in the devenv folder when you run 
'''make env-build'' it does not work with error that  ''./lookup-application.war'' file is missing.

**Comment by manonthegithub** [comment]
true, the Dockerfile for lookup servlet is broken @holycrab13 could you fix the [Dockerfile](https://github.com/dbpedia/databus/blob/master/search/Dockerfile) or maybe the algorithm for running devenv changed?

**Comment by Ayush-Kumar91221** [comment]
does anyone have any idea how to get around it for now ? I am trying to set up the project locally and work on the [issue 129](https://github.com/dbpedia/databus/issues/129) .

**Comment by Ayush-Kumar91221** [comment]
I tried running it but it returns another error:
docker compose up
[+] Running 1/6
 ⠦ virtuoso 4 layers [⠀⠀⠀⠀]      0B/0B      Pulling                                                                         3.6s 
   ⠏ edaedc954fb5 Pulling fs layer                                                                                          0.9s 
   ⠏ 8bc9c228e3da Pulling fs layer                                                                                          0.9s 
   ⠏ 4fe13735df1b Pulling fs layer                                                                                          0.9s 
   ⠏ 4f4fb700ef54 Waiting                                                                                                   0.9s 
 ✘ gstore Error                                                                                                             3.6s 
Error response from daemon: pull access denied for gstore-dev, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
make: *** [Makefile:21: env-start] Error 18

after looking up for it in docker hub i found gstore:dev is something you can install but i could not find gstore-dev. Is it a typo in the docker-compose file? How to get around it

**Comment by manonthegithub** [comment]
Hey @Tethet-18 , yes you should set  `dbpedia/gstore:dev` image,
we have done changes to our envs recently and this broke integrity with documentation

**Comment by Tethet-18** [comment]
updates were made to the docs. However there were some fixes which have been addressed in issue #147. Made PR of its fix
