### ISSUE TITLE
collection wizard search results stay after deleting query terms

### ISSUE THREAD

**Issue by JJ-Author** [dbpedia/databus#17]
the search results can be very messy. I am missing a way to get rid of them, by deleting the query or having an x button or sth.
![image](https://user-images.githubusercontent.com/2630603/156797600-dbcc8e2b-a3b7-43f1-ad50-470f92a1170f.png)

**Comment by JJ-Author** [comment]
probably a bug since they stay even with different query
![image](https://user-images.githubusercontent.com/2630603/156798385-ac45b1c4-9e55-4fed-87ed-fc0ee0d60a48.png)

**Comment by holycrab13** [comment]
fixed in 2.1.0-rc.1
