### ISSUE TITLE
collection wizard filtering hardly usable for big groups/artifacts like DBpedia 

### ISSUE THREAD

**Issue by JJ-Author** [dbpedia/databus#18]
the file list is flooding the view and should be probably limited and then collapsible because I totally lost control and overview by adding generic and mappings group 
![image](https://user-images.githubusercontent.com/2630603/156799536-85050e70-c921-4804-a740-c8986438ba37.png)

**Comment by JJ-Author** [comment]
in general I am super lost here 

-  since the artifact version hierarchy is flat. 
-  the full IRI is a lot of text to read that is redundant
-  the artifacts selections are messy displayed

![image](https://user-images.githubusercontent.com/2630603/156802278-d8bdb5a8-b4b2-4862-a5e3-60a871f6f062.png)

I think for very small groups and artifacts there is better overview now but for big groups and artifacts like dbpedia data there is total loss of overview. I dont know how one could manage the latest-core collection it seems almost impossible in the current stage.

**Comment by holycrab13** [comment]
I will remove the artifact facet in the query generator since it is not the desired workflow.

**Comment by holycrab13** [comment]
Overrides are working similar to the old workflow. Artifacts are not supposed to be used as filters but added as nodes. Overrides can be set on the Artifact nodes.
