### ISSUE TITLE
Default Name

### ISSUE THREAD

**Issue by Vehnem** [dbpedia/databus#20]
Do not use email as default name
Or maybe force user to give full name at account unlock

**Comment by JJ-Author** [comment]
maybe the sub is sometimes (e.g. for auth0) the email? neverthe less in 2.0.10 this still gets indexed in the search as label of the user which is not nice.
![image](https://user-images.githubusercontent.com/2630603/220631046-6610c336-f2d1-49e9-a588-f32a6664169f.png)

**Comment by holycrab13** [comment]
sometimes the OIDC name is set to an email adress. Will add an additional check.

**Comment by holycrab13** [comment]
Account label is now ALWAYS initially set to the account name

**Comment by holycrab13** [comment]
fixed in rc4
