### ISSUE TITLE
collection issues

### ISSUE THREAD

**Issue by JJ-Author** [dbpedia/databus#21]
- [ ] when adding facet selection in faceted browser view to collection reload model from browser storage first before merging models

**Comment by holycrab13** [comment]
Note to self: 
Editing collections in multiple tabs leads to unwanted overrides. A system is needed that keeps a hash in the storage to sync up loaded content of tabs

**Comment by holycrab13** [comment]
A fix for this is in:
Each tab now holds a hash of the collection in memory and checks it against a hash in the local storage. 
*Saving to the local storage also changes the hash in the storage
*Hash mismatch between memory and storage triggers reload from storage

Changing a collection value in one tab now changes the value in all tabs.
