### ISSUE TITLE
Metadata JSON Response for Dataset URI in the Energy Databus

### ISSUE THREAD

**Issue by yum-yab** [dbpedia/databus#22]
In the energy-databus the json-metadata-response is broken and metadata is not returned, so for example 
```
curl -H "Accept: application/jsonld" https://energy.databus.dbpedia.org/chrwm/test/ksz2050_r2_ks80_fugitive_emissions/2022-08-02/
```
returns not the metadata but 
```
{"message":"/gstore/git/chrwm/test/ksz2050_r2_ks80_fugitive_emissions/2022-08-02/dataid.jsonld"}
```

**Note:**

It could be a Bug with mounting since the paths of gstore/git/whatever changed during the updates of the databus.

**Comment by holycrab13** [comment]
Get requests on resources are now either HTML or dynamic RDF generated by virtuoso (any RDF format that virtuoso supports)
