### ISSUE TITLE
groups should be publishable without artifact

### ISSUE THREAD

**Issue by seebi** [dbpedia/databus#24]
our publishing workflow via the cmem-plugin-databus plugin needs an existing group for publishing (or the group is not published but the artifact is)

My suggestion:

allow users to create a group without artifacts
so we can create groups in databus and later publish artifacts via eccenca Corporate Memory
feedback to @yum-yab or @seebi

**Comment by holycrab13** [comment]
2.1.0:
API allows the creation of groups/artifacts
UI now allows the creation of groups without content
UI now also allows editing of already created groups/artifact/version on the respective content pages

**Comment by seebi** [comment]
@holycrab13 nice!

Do you have documentation such as OpenAPI spec somewhere online?

**Comment by holycrab13** [comment]
There is a swagger API documentation on each Databus under `DATABUS_URL/api` with example queries. The document is still under construction and will be fully working in 2.1.0
