### ISSUE TITLE
change github link from dbpedia / databus-maven-plugin to dbpedia / databus

### ISSUE THREAD

**Issue by seebi** [dbpedia/databus#25]
The "Report Issue" link at this page is outdated: https://dev.databus.dbpedia.org/seebi/testing/

wrong: [Report Issue](https://github.com/dbpedia/databus-maven-plugin/issues?q=is%3Aissue+is%3Aopen+label%3Awebsite)
correct: [Report Issue](https://github.com/dbpedia/databus/issues?q=is%3Aissue+is%3Aopen+label%3Awebsite)

**Comment by yum-yab** [comment]
Fixed in https://github.com/dbpedia/databus/pull/27
