### ISSUE TITLE
No underscores allowed in group/artifact

### ISSUE THREAD

**Issue by yum-yab** [dbpedia/databus#28]
Currently it is not possible to use `_` in group/artifact identifier. This limits easy integration since database table names usually don't permit `-` in names, but allow `_`. So it is always necessary to transform names from database -> databus and vice versa.

**Comment by kurzum** [comment]
seems weird as SHACL allows underscores, see: 
https://dbpedia.gitbook.io/databus/model/model/dataid
```
sh:pattern "/[a-zA-Z0-9\\-_]{4,}/[a-zA-Z0-9\\-_\\.]{1,}/[a-zA-Z0-9\\-_\\.]{1,}/[a-zA-Z0-9\\-_\\.]{1,}#Dataset$" ;
```

**Comment by holycrab13** [comment]
now working, added test.
