### ISSUE TITLE
local json context

### ISSUE THREAD

**Issue by kurzum** [dbpedia/databus#3]
http://localhost:3000/system/context.jsonld

**Comment by holycrab13** [comment]
can be closed? context is now on download server and default context url can be set as env variable.

**Comment by holycrab13** [comment]
centralized context was a bad idea due to issues with availability and versioning.

We have to move it back to a local address on each Databus. ASAP!

**Comment by holycrab13** [comment]
new path `/res` is now accessible, gives access to the local context
`res/context.jsonld`
and the shacl files used for data validation (`/res/shacl` folder).
HTML view provides a file browser.

Default context was switched to the local context at `BASE_URL/res/context.jsonld`
