### ISSUE TITLE
Docu Improvements

### ISSUE THREAD

**Issue by kurzum** [dbpedia/databus#30]
* https://dbpedia.gitbook.io/databus/model/model

**Comment by manonthegithub** [comment]
I suggest the followinf structure of the DOCS:
```
# Table of Contents
* Overview
* Use cases
* Running your own Databus Server
  * Run with Docker
  * Configuration
  * HTTPS and Proxy SETUP
* Usage
  * Web Interface
    * Publish
    * Query
    * Collections
  * API
    * Api  DOCS
    * Examples
  * Mods
* Organising your data (Model)
  * Metadata
    * Group
    * Artifact
    * Version
    * Distribution
  * URI Design
  * Versioning
* Development Environment
```

please feel free to propose your improvements!
@kurzum After we decide on the structure we will be able split the chapters between the team members

**Comment by manonthegithub** [comment]
# Table of contents
* [Overview](README.md)
  * [Roadmap](docs/roadmap.md)
* [Use Cases](docs/usecases.md)
  * [🚀 Unique Features (Draft)](docs/uniquesellingpoints.md)
  * [Automated Deployment of DBpedia Services](docs/dbpediadeployment.md)
  * [Building Meta Registries](docs/building-meta-registries.md)
  * [Maven for Data](docs/maven-for-data-manage-data-dependencies-like-code.md)
* Running Your Own Databus Server
  * Run with Docker
  * [Configuration](docs/configuration.md)
  * [HTTPS & Proxy Setup](docs/https-and-proxy-setup.md)
* Usage
  * Web Interface
    * Publish # (That is a comment! Autocompletion of the JSON-LD should be there)
    * [Auto-Completion](docs/auto-completion.md) 
    * Browsing Data # (That is a comment! page for explanations of the web interface) 
    * Collections
  * API
    * [Quickstart Examples (Publish, Download)](docs/quickstart-examples.md)
    * [API Docs](docs/api.md)
  * [Customizing, Mods, Metadata Quality](docs/mods.md)
  * [Databus Client](docs/databus-client.md) 
* [Organising your data (Model)](docs/model.md)
  * [URI Design](docs/uridesign.md)
  * [Versioning](docs/versioning.md)
  * Metadata
    * [Group](docs/group.md)
    * [Artifact](docs/artifact.md)
    * [Version](docs/dataid.md)
    * [Distribution](docs/distribution.md)
  * [Content Variants](docs/content-variants.md)
  * [Persistence (HowTo)](install/persistence-howto.md)
* [Development Environment](devenv/README.md)
