### ISSUE TITLE
content variant and single file addressing requirement error message are hard to understand

### ISSUE THREAD

**Issue by JJ-Author** [dbpedia/databus#36]
it is really hard to debug this error message, almost impossible for big releases like DBpedia:
`All used sub-properties of dataid:contentVariant MUST be used by all dataid:Parts exactly ONCE.` 

useful would be enhancing it with the following insights
- [x] the conent variant that causes the violation
- [x] the files that are missing a value for it
- [x] the files that can not be uniquely adressed grouped into the clusters that are not distinguishable

**Comment by holycrab13** [comment]
Added a new validator BEFORE the SHACL step. Since the SHACL validation for this issue was a little wonky anyway!

Report will now look like this:
```
Invalid content variant setup. Two or more files are not distinguishable by either dataid:formatExtension, dataid:compression or any custom content variant.
[
  {
    "downloadURLs": [
      "https://holycrab13.github.io/webid.ttl",
      "https://raw.githubusercontent.com/dbpedia/webid/master/webid-dbpedia.ttl"
    ],
    "http://dataid.dbpedia.org/ns/core#formatExtension": "ttl",
    "http://dataid.dbpedia.org/ns/core#compression": "none",
    "http://dataid.dbpedia.org/ns/cv#bleb": "asdf"
  }
]
```
