### ISSUE TITLE
Invalid API key name not reported to UI

### ISSUE THREAD

**Issue by white-gecko** [dbpedia/databus#41]
When I try to create an API key in the setting I get no information about invalid characters but also don't get any response when I use invalid characters:

![grafik](https://user-images.githubusercontent.com/1018168/217778392-36945292-e62b-4b7b-a32e-9f745721d151.png)

only the web console/debug tools of my browser help to solve this.

![grafik](https://user-images.githubusercontent.com/1018168/217778329-74425f12-5e2a-45e7-9101-0c52fd177dbc.png)

**Comment by LOVKUSH9888** [comment]
new here anyone guide me here ?

**Comment by holycrab13** [comment]
dashes are okay, but there is a limit on the length of the name - with missing error feedback

**Comment by holycrab13** [comment]
invalid key names are now reported in 2.1.0
(see dev server https://dev.databus.dbpedia.org)
