### ISSUE TITLE
dbpedia-spotlight model wrong URL for FOAF:Person

### ISSUE THREAD

**Issue by Ga11u** [dbpedia/databus#42]
_I open this issue in this project as it does not seem to be a specific active project with an issue tracker for dbpedia-spotlight or dbpedia models._

The Dbpedia Spotlight models and its dockerised services have mapped the URI to FOAF:Person wrong. They report: `Http://xmlns.com/foaf/0.1/Person` with a capital **H** . The correct URI is `http://xmlns.com/foaf/0.1/Person` with lowercase **h**. 

Even though this is a small issue, it is not consistent with the other URIs returned when annotating entities. This can also cause some problems when string matching or parsing the triples in RDF. I think it should be quite straight forward to solve it, as it seems to be a mapping issue in the model or docker-spotlight service.

If there is a better/alternative place to report this issue, let me know.

**Comment by JJ-Author** [comment]
this should go there https://github.com/dbpedia-spotlight/spotlight-docker or the model repo 
unfortunately I can not transfer the issue.
