### ISSUE TITLE
API docs, publishing an artifact.

### ISSUE THREAD

**Issue by manonthegithub** [dbpedia/databus#52]
Trying to reproduce steps from Readme to publish an artifact. Running `docker-compose up`, going to local databus, login as a dbpedia databus user, click user icon -> publish data -> getting "Sorry cant find that!".
Is that linked to auth problem?
How could we make auth smooth for a person wanting just to run the thing for the first time?

**Comment by holycrab13** [comment]
Using the DBpedia account as a default login mechanism for localhost is fine. The issue is not linked to the login but something else (most likely the process that fetches existing groups/artifacts for the user)

**Comment by manonthegithub** [comment]
That also fails on dev databus… Kind regards / Mit freundlichen Grüßen,Kirill Yankov.03.05.2023, в 14:10, holycrab13 ***@***.***> написал(а):﻿
Using the DBpedia account as a default login mechanism for localhost is fine. The issue is not linked to the login but something else (most likely the process that fetches existing groups/artifacts for the user)

**Comment by manonthegithub** [comment]
fixed
