### ISSUE TITLE
Nerd Mode button on Publish page.

### ISSUE THREAD

**Issue by manonthegithub** [dbpedia/databus#53]
I would rename the "nerd mode" button on the Publish data page. -> maybe "plain json-ld mode" or so

**Comment by kurzum** [comment]
https://www.explainxkcd.com/wiki/index.php/806:_Tech_Support
Shibboleet

**Comment by kurzum** [comment]
Add an 🛈 with an explanation.

**Comment by holycrab13** [comment]
Added some information to the header text
