### ISSUE TITLE
Publishing seems broken

### ISSUE THREAD

**Issue by manonthegithub** [dbpedia/databus#55]
Just manually published test single file as a dataset (entered minimal required data in the publish data form)... were no errors on submit.
When I click after publish on the dataset, it is empty https://dev.databus.dbpedia.org/kirikiki/test/

**Comment by manonthegithub** [comment]
executing API method with the sample data, also aerates the same output
<img width="1267" alt="image" src="https://github.com/dbpedia/databus/assets/10817016/c90a59cb-b989-47ae-9165-9c94fe4b27da">


<img width="516" alt="image" src="https://github.com/dbpedia/databus/assets/10817016/4ebeda37-6133-4592-8998-15562083cf7c">

check the dataset here:
https://dev.databus.dbpedia.org/kirikiki/test_group/test_artifact/

**Comment by kurzum** [comment]
re-assess
