### ISSUE TITLE
Publish Wizard Impros (Attribution, Derived From)

### ISSUE THREAD

**Issue by manonthegithub** [dbpedia/databus#61]
I've fund following fields in the publish wizard in the Version section:
<img width="804" alt="image" src="https://github.com/dbpedia/databus/assets/10817016/1f64bcce-6295-4e5a-9ed7-38566dafc409">

These fields (Attribution, Derived From) are unclear. Need some explanation what is expected to be there, I think.

**Comment by manonthegithub** [comment]
#66

**Comment by kurzum** [comment]
Covered by #64
