### ISSUE TITLE
missing DataID download link in the Databus interface

### ISSUE THREAD

**Issue by m1ci** [dbpedia/databus#65]
In the previous version of Databus the DataIDs could be downloaded, but this is no longer the case with the latest version of the Databus.

In fact, the Version webpage do not provide a download link for the DataID.
It only provides the Issue Data and license but not the download link for the DataID. Moreover, there is missing also info for the  Publisher.
Compare: https://dev.databus.dbpedia.org/kirikiki/test_group/test_artifact/2023-06-13/ (new databus)
and https://databus.dbpedia.org/fabian/webids/uniformedWebIds/23-06-20 (old databus)

**Comment by holycrab13** [comment]
Added a download button to the version page.
