### ISSUE TITLE
Consider making authorisation mechanism for reading the metadata

### ISSUE THREAD

**Issue by manonthegithub** [dbpedia/databus#76]

**Comment by kurzum** [comment]
@holycrab13  could you post the options to configure the databus? private-mode=true ? or did you document it somewhere? 
What about hiding the sparql endpoint?

**Comment by holycrab13** [comment]
Needs the environment variable
DATABUS_PRIVATE_MODE=true
SPARQL endpoint is hidden when not logged in. 

Added an entry in the advanced configuration chapter in the gitbook

**Comment by holycrab13** [comment]
Issue can potentially be closed

**Comment by manonthegithub** [comment]
Refs #23
