### ISSUE TITLE
timeline / latest datasets view is missing

### ISSUE THREAD

**Issue by JJ-Author** [dbpedia/databus#78]
would be good to have the timeline / latest uploads for user / group / artifact back (at the moment only on main databus view) maybe this could be done as a tab if its polluting the main UI. but this was quite useful to see new data of colleagues and self evaluate whether the upload worked and therefore quite good feature.

**Comment by holycrab13** [comment]
Okay, felt it was mostly broken / unnessecary, will re-add something similar

**Comment by holycrab13** [comment]
Added a slim interface that displays recent activity of a user on the account page. This uses no cashing and should give users feedback if their last publish attempt was successful.
