### ISSUE TITLE
Provided databus collection not found

### ISSUE THREAD

**Issue by ryabhmd** [dbpedia/databus#79]
Hi! I am trying to set up the DBpedia lookup index using this link to a provided collection (from the lookup repo): https://databus.dbpedia.org/jan/collections/lookup

However, it seems like the link does not work anymore for some reason and I can't access the collection to use. Could you please provide an alternate way to download the collections?

Thanks!

**Comment by manonthegithub** [comment]
Hey! Thank you for reporting! We were doing migration recently and seems that this one was broken.

@holycrab13 could you take a look if that is quickly fixable?

**Comment by holycrab13** [comment]
Changed the documented collection in the lookup repository to:
https://databus.dbpedia.org/janfo/collections/lookup

This new collection should be working again

**Comment by manonthegithub** [comment]
@ryabhmd please check it out and feel free to reopen if its still not working
