### ISSUE TITLE
Unable to download wikidata instance types

### ISSUE THREAD

**Issue by KennyChenBasis** [dbpedia/databus#81]
When I go to https://databus.dbpedia.org/dbpedia/wikidata/instance-types/ and try to download one of the instance types, e.g. the specific one, the link is https://databus.dbpedia.org/dbpedia/wikidata/instance-types/2022.03.01/instance-types_inference=specific.ttl.bzip2, which redirects me to https://downloads.dbpedia.org/repo/dbpedia/wikidata/instance-types/2022.03.01/instance-types_specific.ttl.bz2, but I get "ERR_CONNECTION_REFUSED".

**Comment by KennyChenBasis** [comment]
And the previews don't load, likely for the same reason.

**Comment by manonthegithub** [comment]
Hey! Thank you for reporting! We will fix that ASAP
