### ISSUE TITLE
Conductor page not found from SPARQL page

### ISSUE THREAD

**Issue by KennyChenBasis** [dbpedia/databus#82]
On the SPARQL page https://databus.dbpedia.org/sparql, clicking on the Conductor button leads to https://databus.dbpedia.org/conductor which has a "404: Not Found" error.

**Comment by manonthegithub** [comment]
Thanks for reporting! We are still in the migration stage, sorry for inconvenience :(.

**Comment by kurzum** [comment]
@KennyChenBasis I closed this and put wontfix. At the moment, we are just redirecting to the default Virtuoso SPARQL page. Integrating yasgui or redoing the sparql page completely is a high priority. See #86
