### ISSUE TITLE
API changelog/documentation? backwards-compatibility?

### ISSUE THREAD

**Issue by KennyChenBasis** [dbpedia/databus#83]
Recently, URLs have been changed, breaking backwards-compatibility. Are these changes documented anywhere? And is there some kind of backwards-compatibility policy?

For example, I was programmatically using the SPARQL service to retrieve the URL for the latest Wikidata instance type dumps. However, the SPARQL URL was changed and also the instance type dump URLs were changed. I would think that redirects could help preserve backwards-compatibility.

**Comment by manonthegithub** [comment]
Thanks for your proposal! Unfortunately, we did not plan to support backwards compatibility, but will think on how is best to help you with that.

 It still will need some edits in your SPARQL requests, as we changed the base URI of the ontology. You can check the examples in the docs, all the properties remained the same, but the prefix has changed https://dbpedia.gitbook.io/databus/usage/quickstart-examples#sparql-queries

**Comment by manonthegithub** [comment]
You can also checkout the [Model section](https://dbpedia.gitbook.io/databus/model/metadata/dataid)

**Comment by KennyChenBasis** [comment]
Thanks, feel free to close this issue or leave it open if you want to track it.
