### ISSUE TITLE
Missing files in DBpedia latest-core collection 

### ISSUE THREAD

**Issue by Vehnem** [dbpedia/databus#98]
40 files are missing (not shown) in DBedia lates-core (2022.12.01)

Expecting all files from
https://databus.dbpedia.org/vehnem/replaced-iris/long-abstracts/2022.12.01
https://databus.dbpedia.org/vehnem/replaced-iris/short-abstracts/2022.12.01

to be included in
https://databus.dbpedia.org/dbpedia/collections/dbpedia-snapshot-2022-12

**Comment by holycrab13** [comment]
Okay, currently the filter is set to 20 specific languages. So it works as specified in the collection and might have been bugged before!

100% you want all languages?

**Comment by holycrab13** [comment]
The custom queries are not working with the new Databus version (xsd:string are specified explicitly). Is there a reason why you use a custom query for this? From what I can see, this could be achievable by a normal artifact node.

**Comment by holycrab13** [comment]
The custom queries are not set up correctly. I fixed this for a single snapshot collection, but the rest needs fixes, too. Would be best to do this via script.

**Comment by holycrab13** [comment]
I just discovered an issue (https://github.com/dbpedia/databus/issues/106) working on this task.
That being said, it is unwise to perform a filter on the file name. We should use the content variant setup instead!

**Comment by holycrab13** [comment]
Fixed all snapshot collections and latest core
